name: build
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
  
env:
  NODE_ENV: production
  AVA_FORCE_CI: 'not-ci'

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --also=dev
      - run: npm run postinstall
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm ci --also=dev
      - run: npm run build
      - run: tar cvf - dist | xz -1 > ${{ github.sha }}.${{ github.run_attempt }}.tar.xz
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}.${{ github.run_attempt }}
          path: '*.tar.xz'

  publish:
    needs: build
    if: ${{ success() && (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref_name, 'release'))) }}
    uses: ./.github/workflows/publish_image.yml
    with:
      artifact_name: ${{ github.sha }}.${{ github.run_attempt }}
    secrets: inherit
