name: build
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  workflow_dispatch:
  
env:
  NODE_ENV: production
  AVA_FORCE_CI: 'not-ci'

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --also=dev
      - run: npm run postinstall
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm ci --also=dev
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}.dist
          path: './dist'

  publish:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref_name, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}.dist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ inputs.artifact_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.event.workflow_run.head_branch }}
          labels: ${{ steps.meta.outputs.labels }}

