name: Publish Docker image

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}
on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: ${{ inputs.artifact_name }}

      - name: Extract files from archive
        run: tar -xvf ${{ inputs.artifact_name }}.tar.xz

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ inputs.artifact_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.event.workflow_run.head_branch }}
          labels: ${{ steps.meta.outputs.labels }}
